schema: schema.graphql
exec:
  filename: graph/generated_graph.go
model:
  filename: graph/generated_model.go

models:
  Repository:
    fields:
        bug:
          resolver: true
        allBugs:
          resolver: true
